-- engram: auto-generated loader
-- DO NOT EDIT — regenerated by "just compile"
-- Generated: {{timestamp}}

local engram = {}

-- Auto-reload when compiled files change
require("engram._pathwatcher")

-- Load compiled modules
-- {{modules}}

return engram
